bot:
  username: kotlin_template_bot
  token:
spring:
  flyway:
    baseline-on-migrate: true
  datasource:
    url: jdbc:postgresql://localhost:5432/kotlin_template
    username: postgres
    password: postgres
logging:
  level:
    root: info